# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('css_class', models.CharField(blank=True, max_length=64, null=True, verbose_name='CSS class')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlockTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Optional heading')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='minicms.Block')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Block Translation',
                'db_table': 'minicms_block_translation',
                'db_tablespace': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('is_homepage', models.BooleanField(default=False, verbose_name='Is homepage?')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Assign a code to the page to be able to retrieve or                   link to it independently of the current language,                   slug or position in the page hierarchy', max_length=64, null=True, verbose_name='Code')),
                ('template', models.CharField(blank=True, max_length=255, null=True, verbose_name='Template')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_pages', to='minicms.Page', verbose_name='Parent page')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta title')),
                ('meta_keywords', models.TextField(blank=True, default='', max_length=255, verbose_name='Meta keywords')),
                ('meta_description', models.TextField(blank=True, default='', max_length=255, verbose_name='Meta description')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='minicms.Page')),
            ],
            options={
                'verbose_name': 'Page translaton',
                'db_table': 'minicms_page_translation',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('value', models.TextField(blank=True, max_length=5000, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='blocktranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
